server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    connection-timeout: 50000ms
    servlet:
      context-path: /cold

spring:
  application:
    name: cold-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true  #开启网关拉取nacos的服务
      routes:
        - id: cold-user-router
          uri: lb://cold-user
          predicates:
            - Path=/cold/sys/user/**

        - id: cold-admin-router
          uri: lb://cold-admin
          predicates:
            - Path=/cold/admin/**

        - id: cold-monitor-router
          uri: lb://cold-monitor
          predicates:
            - Path=/cold/device/monitor/**

        - id: cold-jobs-router
          uri: lb://cold-jobs
          predicates:
            - Path=/cold/system/schedule/**

        - id: cold-druid-router
          uri: lb://cold-druid
          predicates:
            - Path=/cold/apache-druid/query/**
logging:
  level:
    #日志打印服务心跳，INFO控制台打印get changedGroupKeys:[]，WARN不打印
    com.alibaba.nacos.client.config.impl: WARN